#modified

use_frameworks!

target 'PodDemo_Example' do
    pod 'PodDemo', :path => '../'
    pod 'Foundation+'
    pod 'OCPodLib'
     pod 'Alamofire',:path => 'Pods/Alamofire.podspec'
     pod 'MJRefresh',:path => 'Pods/MJRefresh.podspec'
     pod 'SideNavigation',:path => 'Pods/SideNavigation.podspec'
    
    target 'PodDemo_Tests' do
        inherit! :search_paths
        
        pod 'FBSnapshotTestCase'
    end
end

