use_frameworks!

target 'PodDemo_Example' do
  pod 'PodDemo', :path => '../'
  pod 'Foundation+'#, :path => 'Specs/Foundation+.podspec'
  pod 'OCPodLib', :path => 'Specs/OCPodLib.podspec'

  target 'PodDemo_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
